In [21]:
from sklearn.preprocessing import OneHotEncoder
import numpy


In [22]:
document = ["my name is vishal I love ai"]

documents = [
    "people watch movie",
    "people watch cricket",
    "people love movie",
    "people love cricket"
]

In [23]:
tokens = [sentence.lower().split() for sentence in documents]
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'love', 'movie'],
 ['people', 'love', 'cricket']]

In [24]:
all_words = [[word] for sentence in tokens for word in sentence]
all_words

[['people'],
 ['watch'],
 ['movie'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['love'],
 ['movie'],
 ['people'],
 ['love'],
 ['cricket']]

In [25]:
encoder = OneHotEncoder(sparse_output=False)

In [26]:
encoder.fit(all_words)
encoder.categories_

[array(['cricket', 'love', 'movie', 'people', 'watch'], dtype=object)]

In [27]:
print("Vocabulary:",encoder.categories_[0])

Vocabulary: ['cricket' 'love' 'movie' 'people' 'watch']


In [30]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])   
    print("\nSentence:",sentence)
    print(encoded_sentence)


Sentence: ['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

Sentence: ['people', 'love', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'love', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [37]:
print(encoder.transform([["love"],["watch"]]))

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
