In [26]:
from dotenv import load_dotenv
load_dotenv(
    r"D:\Vishal Projs\My_Projects\SeptPy\LearningGenerativeAi\.env"
)
import os
os.environ["HUGGINGFACEHUB_API_TOKEN"] = os.getenv("HUGGINGFACEHUB_API_TOKEN")
os.environ["GEMINI_API_KEY"] = os.getenv("GEMINI_API_KEY")
os.environ["OPENAI_API_KEY"] =os.getenv("OPENAI_API_KEY")
# print(os.getcwd())

In [4]:
from sentence_transformers import SentenceTransformer

In [5]:
open_source_embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

In [6]:
text = "Hello"
embedding = open_source_embedding_model.encode(text)


In [7]:
embedding

array([-6.27717450e-02,  5.49587794e-02,  5.21648489e-02,  8.57900083e-02,
       -8.27489123e-02, -7.45729730e-02,  6.85547069e-02,  1.83964521e-02,
       -8.20112824e-02, -3.73848304e-02,  1.21248765e-02,  3.51831806e-03,
       -4.13426291e-03, -4.37844247e-02,  2.18072776e-02, -5.10272104e-03,
        1.95465870e-02, -4.23487090e-02, -1.10359609e-01,  5.42455772e-03,
       -5.57347685e-02,  2.80524399e-02, -2.31587235e-02,  2.84813214e-02,
       -5.37096225e-02, -5.26015684e-02,  3.39392275e-02,  4.53886092e-02,
        2.37184055e-02, -7.31208026e-02,  5.47777042e-02,  1.70472693e-02,
        8.13603923e-02, -2.86273309e-03,  1.19580794e-02,  7.35585466e-02,
       -9.42374691e-02, -8.13620612e-02,  4.00154069e-02,  6.92171510e-04,
       -1.33932913e-02, -5.45381010e-02,  5.15140267e-03, -2.61397716e-02,
        3.68070789e-02, -3.39596197e-02,  2.10932512e-02,  5.59488796e-02,
        5.77813201e-02, -5.41841285e-03, -6.84131682e-02, -9.02369991e-02,
       -4.28667814e-02,  

In [8]:
len(embedding)

384

In [9]:
sentence = "I am enjoying my life"

sentence_Embedding = open_source_embedding_model.encode(sentence)

sentence_Embedding

array([ 1.41958352e-02, -7.63327163e-03,  4.01717834e-02,  3.12327333e-02,
        6.36150986e-02,  4.44374457e-02,  1.51539877e-01,  3.05541996e-02,
       -8.89397133e-03,  9.41626821e-03,  4.47374135e-02, -3.93513963e-02,
        3.29137333e-02, -2.58764275e-03, -1.15002729e-02, -2.18125489e-02,
       -2.09771618e-02, -2.90438589e-02, -1.20578539e-02,  9.97394137e-03,
       -7.92514458e-02,  6.67630881e-02, -2.17446759e-02,  2.94061583e-02,
       -8.49842653e-02,  6.63313940e-02,  1.66632347e-02,  4.80754152e-02,
        8.75426754e-02, -2.81043593e-02, -4.59291823e-02,  3.33275422e-02,
        8.17134753e-02, -1.26605835e-02, -3.82930301e-02,  2.68706307e-02,
       -3.97586683e-03, -9.24846679e-02,  6.48222938e-02, -2.84399875e-02,
       -6.85814535e-04, -5.35817370e-02,  5.74503802e-02, -5.29942773e-02,
        1.81671139e-02, -8.73811543e-03,  1.78119596e-02, -6.26544133e-02,
        1.11724950e-01,  3.16208564e-02, -3.67181599e-02,  3.09978146e-02,
       -6.09221943e-02,  

In [10]:
sentence_Embedding.shape

(384,)

In [11]:
paragraph = "Life is a journey full of challenges, opportunities, and moments of joy. Each day presents new experiences that shape our character and teach us valuable lessons. Sometimes, we encounter obstacles that test our patience and resilience, while at other times, we enjoy successes that bring satisfaction and motivation. Family, friends, and mentors play a crucial role in guiding us through difficult times and celebrating our achievements. By embracing both the highs and lows, we learn to grow, adapt, and appreciate the beauty of life, making every moment meaningful and purposeful"

paragraph_embedding = open_source_embedding_model.encode(paragraph)

paragraph_embedding

array([-8.14277027e-03,  5.70698231e-02, -1.28339883e-02,  2.94348523e-02,
        2.90679764e-02,  2.80469246e-02,  5.37672490e-02, -3.11659239e-02,
        2.79981270e-02, -7.10853264e-02,  3.07776537e-02,  3.27620422e-03,
        3.10913976e-02,  1.71860494e-02, -2.87055355e-02,  8.58180504e-03,
       -1.15415588e-01,  1.20500363e-02, -6.14062622e-02, -1.81598794e-02,
       -7.18009248e-02, -3.79333943e-02, -1.81216914e-02,  6.50393888e-02,
       -9.25657302e-02,  5.15655577e-02, -4.21887264e-02, -1.09481262e-02,
       -2.75625568e-03, -1.61892753e-02,  3.76701243e-02, -2.12171897e-02,
        6.71514049e-02,  1.29004633e-02,  3.78542133e-02,  1.17134042e-01,
        6.61491305e-02, -1.49231087e-02,  4.38310988e-02,  1.82311106e-02,
       -1.92793421e-02, -1.76311098e-02,  3.14888209e-02, -2.06367187e-02,
        5.53693343e-03, -5.44303656e-02,  1.94410386e-03, -4.28863689e-02,
        1.97311137e-02, -1.25855105e-02, -6.74980581e-02, -3.76759432e-02,
       -3.65880430e-02, -

In [12]:
len(paragraph_embedding)

384

In [13]:
from langchain_huggingface import HuggingFaceEmbeddings

In [14]:
from huggingface_hub import InferenceClient
import os

# client = InferenceClient(
#     api_key=os.getenv("HUGGINGFACEHUB_API_TOKEN")
# )

# embedding = client.feature_extraction(
#     "What is artificial intelligence?",
#     model="BAAI/bge-m3"
# )

print(embedding)


[-6.27717450e-02  5.49587794e-02  5.21648489e-02  8.57900083e-02
 -8.27489123e-02 -7.45729730e-02  6.85547069e-02  1.83964521e-02
 -8.20112824e-02 -3.73848304e-02  1.21248765e-02  3.51831806e-03
 -4.13426291e-03 -4.37844247e-02  2.18072776e-02 -5.10272104e-03
  1.95465870e-02 -4.23487090e-02 -1.10359609e-01  5.42455772e-03
 -5.57347685e-02  2.80524399e-02 -2.31587235e-02  2.84813214e-02
 -5.37096225e-02 -5.26015684e-02  3.39392275e-02  4.53886092e-02
  2.37184055e-02 -7.31208026e-02  5.47777042e-02  1.70472693e-02
  8.13603923e-02 -2.86273309e-03  1.19580794e-02  7.35585466e-02
 -9.42374691e-02 -8.13620612e-02  4.00154069e-02  6.92171510e-04
 -1.33932913e-02 -5.45381010e-02  5.15140267e-03 -2.61397716e-02
  3.68070789e-02 -3.39596197e-02  2.10932512e-02  5.59488796e-02
  5.77813201e-02 -5.41841285e-03 -6.84131682e-02 -9.02369991e-02
 -4.28667814e-02  2.36527268e-02  1.21493533e-01  3.23928185e-02
 -2.26593968e-02 -2.32817400e-02  4.88659739e-02 -5.93515858e-02
 -3.40660252e-02  3.59626

In [20]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings

In [21]:
google_embedding_model = GoogleGenerativeAIEmbeddings(model='gemini-embedding-001' )

In [22]:
google_embedding = google_embedding_model.embed_query("Hello we are creating a new world using ai")

In [23]:
google_embedding

[-0.01497277,
 -0.0031133369,
 0.027060065,
 -0.053968407,
 -0.006662171,
 -0.013343108,
 0.009670777,
 0.013498677,
 0.018701147,
 -0.011189085,
 -0.011803841,
 -0.010954971,
 0.039558254,
 0.054054618,
 0.14388406,
 0.0021200792,
 0.007763182,
 0.005584817,
 -0.006427928,
 -0.0020900038,
 -0.0070273825,
 -0.0141474195,
 0.030403614,
 -0.0076806513,
 -0.01572095,
 0.0044076107,
 0.022015356,
 -0.010326944,
 -0.0036257121,
 0.0032874616,
 0.020820552,
 -0.0057244194,
 -0.00843811,
 0.015886832,
 -0.00026386595,
 0.028634427,
 0.0314535,
 -0.006256575,
 -0.020896195,
 0.0056114136,
 -0.00569897,
 0.014789241,
 -0.032297947,
 -0.015771877,
 0.010458628,
 0.0063787266,
 0.0034865194,
 -0.038196288,
 0.0018486453,
 0.034864243,
 -0.014683287,
 -0.012250818,
 -0.009086237,
 -0.14977731,
 -0.022764726,
 0.022023248,
 0.009772925,
 -0.0008221558,
 0.01580895,
 -0.018671649,
 -0.008595799,
 0.010463972,
 -0.007769453,
 -0.021762853,
 -0.019503033,
 -0.033664964,
 -0.00019466817,
 -0.017639473,

In [24]:
len(google_embedding)

3072

In [27]:
from langchain_openai import OpenAIEmbeddings

In [30]:
openai_embeddings_model=OpenAIEmbeddings(model="text-embedding-3-large")

In [ ]:
# embedding = openai_embeddings_model.embed_query("What is the capital of France?") no balance to execute

In [33]:
openai_embedding_small_model = OpenAIEmbeddings(model='text-embedding-3-small')

In [34]:
openai_embedding = openai_embedding_small_model.embed_query("You are taking lots of money")

RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}

In [ ]:
openai_embedding

In [ ]:
len(openai_embedding)

TEXT

IMAGE?

ViT(vision transformer) and CLIP(contrastive language-image pretraining) are two popular transformer-based models used for image processing tasks.

In [35]:
from transformers import CLIPModel, CLIPProcessor

In [37]:
from PIL import Image

In [38]:
image = Image.open(r'D:\Vishal Projs\My_Projects\SeptPy\LearningGenerativeAi\public\images\MachineImg.png')

In [42]:
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

d:\Vishal Projs\My_Projects\SeptPy\LearningGenerativeAi\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\USER\.cache\huggingface\hub\models--openai--clip-vit-base-patch32. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [45]:
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Error while downloading from https://huggingface.co/openai/clip-vit-base-patch32/resolve/main/pytorch_model.bin: HTTPSConnectionPool(host='us.aws.cdn.hf.co', port=443): Read timed out.
Trying to resume download...
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


In [49]:
inputs = processor(images=image, return_tensors='pt')

In [50]:
import torch

In [51]:
with torch.no_grad():
    image_embedding = model.get_image_features(**inputs)

In [52]:
image_embedding

tensor([[-1.8085e-01, -2.0125e-01, -2.2910e-01, -3.4626e-01,  2.3899e-01,
         -3.6232e-01,  2.0086e-01, -3.1316e-01, -3.0641e-01,  2.6625e-01,
          9.7419e-02, -2.5336e-01,  2.9407e-01,  4.7295e-01, -2.6323e-02,
         -3.4747e-01,  1.1681e+00,  1.0018e-01, -3.3311e-01,  3.6249e-02,
          4.2546e-01,  3.4548e-02,  3.8243e-02,  2.9788e-01, -3.6186e-01,
          1.9370e-01,  1.9108e-01,  2.5868e-01, -3.2912e-01, -1.5239e-03,
          9.0124e-02, -8.3572e-02, -4.9760e-01, -1.0339e-01,  1.1237e-02,
         -2.5695e-01, -1.2232e-02, -1.5479e-01, -1.0174e-01, -2.0270e+00,
          4.3334e-02, -3.0499e-01, -2.2207e-01, -2.0999e-01,  5.2312e-01,
         -1.2095e+00, -2.9818e-01,  1.9953e-01, -7.3153e-01,  3.4682e-02,
          3.8936e-02,  3.9599e-01,  1.6756e-01, -4.5581e-01, -2.9982e-01,
          1.2089e-01, -3.3281e-01, -3.5713e-01,  3.5794e-02,  9.0551e-02,
          6.5675e-01, -7.5594e-03,  1.8231e-01,  6.1722e-01,  1.5618e-01,
         -1.8477e-01,  5.0499e-01, -2.